apiVersion: apps/v1
kind: Deployment
metadata:
  name: aap-server
  namespace: agent2-airgap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aap-server
  template:
    metadata:
      labels:
        app: aap-server
    spec:
      containers:
      - name: aap-server
        image: quay.io/fayez2016/aap-server:staging
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: aap-server
  namespace: agent2-airgap
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: aap-server
